### ISSUE TITLE
Error al iniciar

### ISSUE THREAD

**Issue by AlbertMorenoDEV** [GeekyTheory/Raspberry-Pi-Status#5]
module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module 'socket.io-client'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/home/pi/git/Raspberry-Pi-Status/node_modules/socket.io/lib/socket.io.js:12:14)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:32)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)

He probado con:
sudo npm install socket.io -g
npm install socket.io

**Comment by MiguelCatalan** [comment]
Buscando un poco parece que lo que te falta es *'socket.io-client'* y los comandos que has puesto te instalar la versión *server*.

	npm install socket.io-client

**Comment by AlbertMorenoDEV** [comment]
Era eso, muchas gracias! ;)
